### ISSUE TITLE
Names of the people are far away

### ISSUE THREAD

**Issue by Filtik** [H-uru/Plasma#1620]
Hello again.
I've seen something like this several times but didn't think it was that important, but I think it should be fixed.
If you move the cursor over someone, the person's name appears.

For me, the name is very far away, see picture.

<img width="962" alt="2024-10-15 14_34_23-The Open Cave" src="https://github.com/user-attachments/assets/dd05e729-13a3-4d6e-8275-8b913c293b14">

I started the game once in full screen and window mode but there was no difference.

For your information:
I have 3 monitors. 2x 1920x1080 and 1x 4k = 3840x2160 (main monitor) resolution.

Thanks for your work and if I knew more about C++, I would fix this myself ;)

**Comment by Hoikas** [comment]
Well that's exciting. Do you have display scaling enabled in Windows, by any chance?

![image](https://github.com/user-attachments/assets/1cbf4bb9-37ab-4081-bbdf-5773bf5a457e)

**Comment by Filtik** [comment]
Yes, I have the scale at 150%

**Comment by patmauro** [comment]
Having had similar issues before, I'm _fairly_ certain this should be resolved by the Backing Scale changes from https://github.com/H-uru/Plasma/pull/1269 - bear in mind these are only in the H'uru client at the moment and haven't made it downstream to the other versions of the client out there (Gehn, etc). Are you able to reproduce the issue with a fresh build of the H'uru client? (You might have to hook this up to the Destiny shard or something like that to confirm.)

**Comment by Mirphak** [comment]
I confirm it's a Windows "Scale and layout" effect related to https://github.com/H-uru/Plasma/pull/1269.
Example, at 100%
![image](https://github.com/user-attachments/assets/fe0438ff-a06c-4d35-9527-f874626cd8ad)
at 150%
![image](https://github.com/user-attachments/assets/9afae5c5-d98f-434e-b990-049b05c4ab18)

**Comment by dpogue** [comment]
FWIW, I am still seeing this in wine with an up-to-date build and no DPI scaling configured in winecfg

![Image](https://github.com/user-attachments/assets/cb381ec5-ff7b-4834-ac53-eb4ed2a448a3)
